In [10]:
import torch 

In [34]:
x = torch.zeros(5,3)
y = torch.ones(4,5)
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


In [35]:
x = x.view(-1,5)  # just like the reshape funtion in numpy

In [38]:
b = x.numpy()    # convert tensor to numpy

In [41]:
x = torch.from_numpy(b)  # convert numpy to pytorch tensor

In [44]:
a = torch.ones(5,4)
b = torch.ones(4,8)
mat_mul = torch.mm(a,b)

In [45]:
print(mat_mul)

tensor([[4., 4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4., 4., 4., 4.]])


In [53]:
batch1 = torch.randn(10,3,4)
batch2 = torch.randn(10,4,5)
result = torch.bmm(batch1,batch2)  # batch multiplication

In [56]:
result.shape

torch.Size([10, 3, 5])

In [99]:
# Computational Graph

x = torch.ones(2,2)
y = torch.ones(2,1)
y[1][0] = 0
w = torch.randn(2,1, requires_grad = True)
b = torch.randn(1,requires_grad = True)

In [120]:
p = torch.sigmoid(torch.mm(x,w) + b)

In [121]:
loss = -y*torch.log(p)- (1-y)*torch.log(1-p)

In [122]:
cost = loss.mean()

In [123]:
cost.backward()

In [124]:
print(w.grad)
print(b.grad)

tensor([[0.8212],
        [0.8212]])
tensor([0.8212])


In [145]:
from torch import nn
import torch.optim as optim

In [138]:
class Logistic_Regression(nn.Module):
    def __init__(self,input_dim,hidden_dim):
        super(Logistic_Regression,self).__init__()
        self.linear1 = nn.Linear(input_dim,hidden_dim)   # these linear1 and linear2 are callable variables that will be called in forward method
        self.linear2 = nn.Linear(hidden_dim,1)
    def forward(self,x):
        x = self.linear1(x)    # train set will be passed to this callable variable that triggers nn.Linear function here z (weighted sum) will be computed for linear1 layer
        x = torch.relu(x)
        x = self.linear2(x)
        output = torch.sigmoid(x)
        return output
        

In [139]:
input_dim = 12
hidden_dim = 4
model = Logistic_Regression(input_dim,hidden_dim)

In [157]:
criterion = nn.BCELoss()

In [158]:
optimizer = torch.optim.SGD(model.parameters(),lr=0.01)

In [159]:
x_train = torch.randn(100,input_dim)
y_train = torch.randint(0,2,(100,1)).float()

In [160]:
model.train()

Logistic_Regression(
  (linear1): Linear(in_features=12, out_features=4, bias=True)
  (linear2): Linear(in_features=4, out_features=1, bias=True)
)

In [257]:
for epoch in range(1):
    optimizer.zero_grad()
    y_pred = model(x_train)   # this line triggers the forward function in Logistic regression
    loss = criterion(y_pred,y_train)   # it computes the loss between prediction and ground truth
    loss.backward()       # it computes the gradient based on the loss using backward propagation
    optimizer.step()
    print(f'Epoch [{epoch+1}], Loss: {loss.item():.4f}')

Epoch [1], Loss: 0.5574
